### ISSUE TITLE
Errors when trying to pull in third party scripts

### ISSUE THREAD

**Issue by mcat** [Trott/grunt-html-smoosher#2]
Throws errors when third party scripts are encountered.

```
Fatal error: Unable to read "build///use.typekit.net/vyq8gyq.js" file (Error code: ENOENT).
```

A few examples when this happens:
- Google Jquery Library
- Typekit

**Comment by benbreedlove** [comment]
Should be fixed in a pull, changeset d1bc719826dcf57028f215a6920ade0917fd2d8a
