### ISSUE TITLE
not possible to install with node 0.12.1 and npm 2.5.1

### ISSUE THREAD

**Issue by Davst** [Trott/grunt-html-smoosher#23]
Seems like the package can't currently be installed at least on OSX

npm install grunt-html-smoosher --save-dev
npm ERR! Darwin 14.1.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "grunt-html-smoosher" "--save-dev"
npm ERR! node v0.12.1
npm ERR! npm  v2.5.1
npm ERR! code ETARGET

npm ERR! notarget No compatible version found: uglifyjs@'>=2.3.6 <2.4.0'
npm ERR! notarget Valid install targets:
npm ERR! notarget ["2.4.10"]
npm ERR! notarget 
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

**Comment by Trott** [comment]
I've published `grunt-html-smoosher-install-fix` to address this. Change 'grunt-html-smoosher' in your package.json and in the call to `grunt.loadNpmTasks` in your Gruntfile and that should do it. 

Hopefully, I can deprecate that package soon and the fix will be here or in someone's fork of this project.

**Comment by Trott** [comment]
This is now fixed in grunt-html-smoosher 0.1.4.
